import type {
  Booking,
  ManagementUser,
  NotificationItem,
  Resource,
  Ticket,
} from "./types";

export const initialResources: Resource[] = [
  {
    id: "r1",
    name: "Lecture Hall A-101",
    location: "Building A, Floor 1",
    type: "Lecture Hall",
    capacityLabel: "Capacity: 120",
    status: "ACTIVE",
    accent: "blue",
    icon: "building",
  },
  {
    id: "r2",
    name: "Computer Lab B-201",
    location: "Building B, Floor 2",
    type: "Lab",
    capacityLabel: "Capacity: 40",
    status: "ACTIVE",
    accent: "purple",
    icon: "lab",
  },
  {
    id: "r3",
    name: "Meeting Room C-105",
    location: "Building C, Floor 1",
    type: "Meeting Room",
    capacityLabel: "Capacity: 12",
    status: "ACTIVE",
    accent: "green",
    icon: "meeting",
  },
  {
    id: "r4",
    name: "Projector #3",
    location: "Building A, Storage",
    type: "Equipment",
    capacityLabel: "Portable",
    status: "OUT_OF_SERVICE",
    accent: "orange",
    icon: "projector",
  },
  {
    id: "r5",
    name: "Auditorium Main",
    location: "Main Building, Ground",
    type: "Lecture Hall",
    capacityLabel: "Capacity: 500",
    status: "ACTIVE",
    accent: "blue",
    icon: "building",
  },
  {
    id: "r6",
    name: "Camera Kit #1",
    location: "Media Center",
    type: "Equipment",
    capacityLabel: "Portable",
    status: "ACTIVE",
    accent: "orange",
    icon: "camera",
  },
];

export const initialBookings: Booking[] = [
  {
    id: "b1",
    resourceName: "Lab A-201",
    dateTime: "Apr 5, 09:00 - 11:00",
    purpose: "Guest Lecture",
    attendees: 35,
    status: "PENDING",
  },
  {
    id: "b2",
    resourceName: "Meeting Room C-105",
    dateTime: "Apr 6, 14:00 - 16:00",
    purpose: "Staff Meeting",
    attendees: 8,
    status: "APPROVED",
  },
  {
    id: "b3",
    resourceName: "Auditorium Main",
    dateTime: "Apr 8, 10:00 - 12:00",
    purpose: "Annual Seminar",
    attendees: 200,
    status: "PENDING",
  },
  {
    id: "b4",
    resourceName: "Projector #3",
    dateTime: "Apr 4, 13:00 - 15:00",
    purpose: "Presentation",
    attendees: 50,
    status: "REJECTED",
    actionNote: "Resource unavailable",
  },
  {
    id: "b5",
    resourceName: "Computer Lab B-201",
    dateTime: "Apr 3, 08:00 - 10:00",
    purpose: "Lab Session",
    attendees: 30,
    status: "CANCELLED",
    actionNote: "By user",
  },
];

export const initialTickets: Ticket[] = [
  {
    id: "t1",
    number: "#1024",
    title: "Projector not working - Room C-301",
    subtitle: "Equipment Failure • Building C, Room 301",
    priority: "HIGH",
    status: "IN_PROGRESS",
    reportedBy: "Jane Smith",
    assignedTo: "Mike Tech",
    comments: 2,
  },
  {
    id: "t2",
    number: "#1023",
    title: "AC not cooling - Lab B-201",
    subtitle: "HVAC • Building B, Floor 2",
    priority: "MEDIUM",
    status: "OPEN",
    reportedBy: "John Doe",
    assignedTo: null,
    comments: 0,
  },
  {
    id: "t3",
    number: "#1022",
    title: "Broken chair - Lecture Hall A",
    subtitle: "Furniture • Building A, Lecture Hall",
    priority: "LOW",
    status: "RESOLVED",
    reportedBy: "Sarah Lee",
    assignedTo: "Tom Fix",
    comments: 3,
  },
  {
    id: "t4",
    number: "#1021",
    title: "Network outage - Building D",
    subtitle: "Network • Building D",
    priority: "CRITICAL",
    status: "CLOSED",
    reportedBy: "Ops Team",
    assignedTo: "Net Admin",
    comments: 8,
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: "n1",
    title: "Booking Approved",
    body: "Your booking for Lab A-201 on Apr 5 has been approved.",
    time: "2 minutes ago",
    kind: "success",
    read: false,
  },
  {
    id: "n2",
    title: "Ticket Status Updated",
    body: "Ticket #1024 changed to IN_PROGRESS.",
    time: "15 minutes ago",
    kind: "warning",
    read: false,
  },
  {
    id: "n3",
    title: "New Comment",
    body: "John added a comment on your ticket.",
    time: "1 hour ago",
    kind: "info",
    read: false,
  },
];

export const initialManagementUsers: ManagementUser[] = [
  {
    id: "u1",
    name: "Admin User",
    email: "admin@smartcampus.edu",
    role: "ADMIN",
    joined: "Mar 1, 2026",
    initial: "A",
    avatarClass: "bg-blue-100 text-blue-700",
  },
  {
    id: "u2",
    name: "Jane Smith",
    email: "jane@smartcampus.edu",
    role: "USER",
    joined: "Mar 5, 2026",
    initial: "J",
    avatarClass: "bg-green-100 text-green-700",
  },
  {
    id: "u3",
    name: "Mike Tech",
    email: "mike@smartcampus.edu",
    role: "TECHNICIAN",
    joined: "Mar 10, 2026",
    initial: "M",
    avatarClass: "bg-yellow-100 text-yellow-700",
  },
  {
    id: "u4",
    name: "John Doe",
    email: "john@smartcampus.edu",
    role: "USER",
    joined: "Mar 12, 2026",
    initial: "J",
    avatarClass: "bg-red-100 text-red-700",
  },
];
