server:
  port: 8080

spring:
  application:
    name: smart-campus-hub
  datasource:
    url: jdbc:mysql://localhost:3306/smart_campus?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  cors:
    allowed-origins: "http://localhost:3000"

logging:
  level:
    org.hibernate.SQL: warn
